### ISSUE TITLE
Enhance Item for storage of full JSON API response

### ISSUE THREAD

**Issue by bmxp** [jentz1986/shng-owm-plugin#5]
It would be great to be able to define an item to receive the result of the API call for own processing in a logic.

like
```
myowmonecall:
    type: str
    owm_response: onecall

my_weather_api_response_item:
    type: str
    owm_response: weather
```
