### ISSUE TITLE
Plugin.yaml contains double keys for de

### ISSUE THREAD

**Issue by bmxp** [jentz1986/shng-owm-plugin#6]
The last sections in plugin.yaml have doubled definitions for german info ``de`` instead of ``en``´marked with #here:

```
plugin_functions:
    # Definition of function interface of the plugin
    get_value:
        type: void
        description:
            de: "Lädt einen Wert"
            en: "Reads a value"
        parameters:
            owm_matchstring:
                type: str
                description:
                    de: "Zum Beispiel /day/0/rain"
                    en: "E.g. /day/0/rain"
    
    get_beaufort_description:
        type: str
        description:
            de: ""
            en: ""
        parameters:
            speed_in_bft:
                type: num
                description:
                    de: "Windstärke in bft, integer zwischen 0 und 12"
                    en: "Wind-speed in bft, integer between 0 und 12"
    
    get_beaufort_number:
        type: num
        description:
            de: "Berechnet den Beaufort-Wert (0 - 12) aus der Windgeschwindigkeit in m/s"
            en: "Translates a wind-speed from m/s to beaufort-scale (0 - 12)"     # here
        parameters:
            speed_in_mps:
                type: num
                description:
                    de: "Windstärke in m/s"
                    en: "Wind-speed in m/s"         # here

```
